#!/usr/bin/env bash
# Configures users + sshd for ROLE={bastion|bastion2|target|sftp-off|auth|http}
# and starts auxiliary HTTP/UDS listeners where needed.

set -euo pipefail

ROLE="${ROLE:-target}"
LAB_PASSWORD="${LAB_PASSWORD:-easy}"
# Prefer bind-mounted /keys when readable; otherwise use keys baked into the image
# (avoids rootless Podman/SELinux bind-mount issues across many containers).
KEYS_DIR="${KEYS_DIR:-}"
if [[ -z "$KEYS_DIR" ]]; then
  if [[ -r /keys/authorized_keys ]]; then
    KEYS_DIR=/keys
  else
    KEYS_DIR=/opt/lab/keys
  fi
fi
AUTH_KEYS_FILE="${KEYS_DIR}/authorized_keys"
PUBKEY_FILE="${KEYS_DIR}/id_ed25519.pub"

log() { printf '[lab:%s] %s\n' "$ROLE" "$*"; }

install_authorized_keys() {
  local user="$1"
  local dest="/home/${user}/.ssh/authorized_keys"
  if [[ -f "$AUTH_KEYS_FILE" ]]; then
    install -m 600 -o "$user" -g "$user" "$AUTH_KEYS_FILE" "$dest"
  elif [[ -f "$PUBKEY_FILE" ]]; then
    install -m 600 -o "$user" -g "$user" "$PUBKEY_FILE" "$dest"
  else
    log "WARN: no keys in ${KEYS_DIR}; pubkey auth will fail until scripts/generate-keys.sh is run"
    : >"$dest"
    chown "$user:$user" "$dest"
    chmod 600 "$dest"
  fi
}

install_host_keys() {
  local role="$1"
  local src="/opt/lab/host-keys/${role}"
  if [[ -d "$src" && -f "${src}/ssh_host_ed25519_key" ]]; then
    install -m 600 "${src}/ssh_host_rsa_key" /etc/ssh/ssh_host_rsa_key
    install -m 644 "${src}/ssh_host_rsa_key.pub" /etc/ssh/ssh_host_rsa_key.pub
    install -m 600 "${src}/ssh_host_ecdsa_key" /etc/ssh/ssh_host_ecdsa_key
    install -m 644 "${src}/ssh_host_ecdsa_key.pub" /etc/ssh/ssh_host_ecdsa_key.pub
    install -m 600 "${src}/ssh_host_ed25519_key" /etc/ssh/ssh_host_ed25519_key
    install -m 644 "${src}/ssh_host_ed25519_key.pub" /etc/ssh/ssh_host_ed25519_key.pub
    log "installed stable host keys from ${src}"
  else
    log "using image-generated host keys (run scripts/generate-host-keys.sh for stable keys)"
  fi
}

ensure_user() {
  local user="$1"
  local shell="${2:-/bin/bash}"
  if ! id -u "$user" >/dev/null 2>&1; then
    useradd -m -s "$shell" "$user"
  fi
  echo "${user}:${LAB_PASSWORD}" | chpasswd
  mkdir -p "/home/${user}/.ssh" "/home/${user}/sandbox-data"
  chmod 700 "/home/${user}/.ssh"
  install_authorized_keys "$user"
  chown -R "$user:$user" "/home/${user}"
}

install_sshd_config() {
  local name="$1"
  local src="/opt/lab/sshd/${name}.conf"
  if [[ ! -f "$src" ]]; then
    log "ERROR: missing sshd profile ${src}"
    exit 1
  fi
  # Replace the package sshd_config entirely so role knobs (esp. Subsystem)
  # are not overridden by the stock Ubuntu file after Include.
  {
    cat <<'EOF'
# Generated by lab-entrypoint — do not edit inside the container.
Port 22
ListenAddress 0.0.0.0
AddressFamily inet
UseDNS no
PermitRootLogin no
PrintMotd no
AcceptEnv LANG LC_*
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
EOF
    cat "$src"
  } >/etc/ssh/sshd_config
  rm -f /etc/ssh/sshd_config.d/*.conf 2>/dev/null || true
}

start_http_helpers() {
  mkdir -p /run/lab
  chmod 755 /run/lab
  python3 /opt/lab/http_tcp.py --bind 0.0.0.0 --port 8080 --label "$ROLE" &
  python3 /opt/lab/http_uds.py --socket /run/lab/http.sock --label "$ROLE" &
  # World-accessible socket path for StreamLocal forwarding tests.
  # (Permissions tightened after bind inside the script; re-chmod for lab users.)
  sleep 0.3
  if [[ -S /run/lab/http.sock ]]; then
    chmod 666 /run/lab/http.sock || true
  fi
}

case "$ROLE" in
  http)
    log "starting HTTP-only backend on :8080"
    exec python3 /opt/lab/http_tcp.py --bind 0.0.0.0 --port 8080 --label http-backend
    ;;

  bastion|bastion2)
    ensure_user easy
    ensure_user keyuser
    install_host_keys "$ROLE"
    install_sshd_config "$ROLE"
    ;;

  target)
    ensure_user easy
    ensure_user keyuser
    install_host_keys target
    install_sshd_config target
    start_http_helpers
    # Sample tree for SFTP browse / recursive transfer checks.
    mkdir -p /home/easy/sandbox-data/{docs,uploads}
    echo "hello from target" >/home/easy/sandbox-data/docs/readme.txt
    chown -R easy:easy /home/easy/sandbox-data
    ;;

  sftp-off)
    ensure_user easy
    ensure_user keyuser
    install_host_keys sftp-off
    install_sshd_config sftp-off
    mkdir -p /home/easy/sandbox-data
    echo "scp-fallback host" >/home/easy/sandbox-data/readme.txt
    chown -R easy:easy /home/easy/sandbox-data
    ;;

  auth)
    ensure_user easy
    ensure_user keyuser
    ensure_user kbdint
    # keyonly: pubkey only (password locked out via sshd Match)
    ensure_user keyonly
    # passonly: password only (no authorized_keys)
    ensure_user passonly
    : >/home/passonly/.ssh/authorized_keys
    chown passonly:passonly /home/passonly/.ssh/authorized_keys
    chmod 600 /home/passonly/.ssh/authorized_keys
    install_host_keys auth
    install_sshd_config auth
    ;;

  *)
    log "ERROR: unknown ROLE='${ROLE}'"
    exit 1
    ;;
esac

if [[ "$ROLE" != "http" ]]; then
  log "validating sshd config"
  /usr/sbin/sshd -t
  log "starting sshd (foreground)"
  # -D: do not daemonize (PID 1 stays sshd); -e: log to stderr for compose.
  exec /usr/sbin/sshd -D -e
fi
